### ISSUE TITLE
Removed from Chrome

### ISSUE THREAD

**Issue by dtantono1** [yashagarwal1411/SubtitlesForYoutube#47]
Hi
I checked the extension and it said it is removed because of the malware. Is it true?
![image](https://github.com/yashagarwal1411/SubtitlesForYoutube/assets/86941934/320a89d9-d164-47ab-ad36-5d0d90e9a5d0)

**Comment by yashagarwal1411** [comment]
NOTE: The existing extension on Chrome Web Store has been transferred to another user [helloite5555556@gmail.com](mailto:helloite5555556@gmail.com) on July 1st, 2023. Please reach out to them directly for any further support requests.

**Comment by TheMrRandomDude** [comment]
@dtantono1 Do you happen to have it still disabled or the crx file? I removed it before checking it's permissions, I'm curious how much it has seen so far.

**Comment by gixid192** [comment]
I know that you are no longer maintain this extension. But the new extension in Chrome Store is removed due to containing malware. So I just write here for those who came after scanning the new extension via VirtusTotal or similar sites.

I checked the new extension and **it actually does contains malware**. _Do not install new version, just download the source here and install it from this repo._

If anyone want to check, just open manifest.json, content_script section, it is now added 3 more sites: facebook, twitter, linkedin.
The code I found that actually messing with facebook is in js/background.bundle.js, I didn't go further as this is enough for me to confirm the extension is modified to steal accounts.
